[package]
name = "thmbox"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["s15n <@s15n>"]
license = "LGPL-3.0-or-later"
description = "Creating beautiful theorem environments in typst with ease."
repository = "https://github.com/s15n/typst-thmbox"
keywords = [ "theorem", "proof" ]
categories = [ "components" ] # "languages"
exclude = ["/gallery/*"]